const express=require('express');const cors=require('cors');const {spawn}=require('child_process');const path=require('path');
const app=express();const PORT=process.env.PORT||3000;
app.use(cors());app.use(express.json({limit:'2mb'}));app.use(express.urlencoded({extended:true,limit:'2mb'}));
let apiReady=false;let cli=process.env.HTTPIE_BIN||'http';
function checkHttpie(){return new Promise(resolve=>{const p=spawn(cli,['--version']);let out='';p.stdout.on('data',d=>out+=d);p.on('close',c=>{apiReady=c===0;console.log(`[KELL] HTTPie status: ${apiReady?'ONLINE':'OFFLINE'}${out.trim()?` (${out.trim()})`:''}`);resolve(apiReady)});p.on('error',()=>{apiReady=false;console.log('[KELL] HTTPie status: OFFLINE');resolve(false)})})}
app.get('/api/status',(req,res)=>res.json({ok:apiReady,status:apiReady?'online':'offline',engine:'HTTPie CLI'}));
app.post('/api/request',async(req,res)=>{if(!apiReady)return res.status(503).json({ok:false,error:'HTTPie engine is offline'});const b=req.body||{};if(!b.url)return res.status(400).json({ok:false,error:'URL is required'});let args=[];const method=(b.method||'GET').toUpperCase();args.push('--check-status','--ignore-stdin','--print=Hhb','--timeout',String(Math.min(Number(b.timeout)||30,120)),method,b.url);if(b.headers&&typeof b.headers==='object')for(const [k,v] of Object.entries(b.headers)){if(v!==undefined&&v!==null)args.push(`${k}:${v}`)}if(b.query&&typeof b.query==='object'){for(const [k,v] of Object.entries(b.query)){const u=new URL(b.url);u.searchParams.set(k,String(v));args[args.indexOf(b.url)]=u.toString()}}
if(b.body!==undefined&&['POST','PUT','PATCH','DELETE'].includes(method)){let body=typeof b.body==='string'?b.body:JSON.stringify(b.body);args.push(`--raw=${body}`);if(!Object.keys(b.headers||{}).some(k=>k.toLowerCase()==='content-type'))args.push('Content-Type:application/json')}
const started=Date.now();const p=spawn(cli,args,{env:process.env});let stdout='',stderr='';p.stdout.on('data',d=>stdout+=d);p.stderr.on('data',d=>stderr+=d);p.on('error',e=>res.status(500).json({ok:false,error:e.message}));p.on('close',code=>{const elapsed=Date.now()-started;let header='',body=stdout;const split=stdout.split(/\r?\n\r?\n/);if(split.length>1){header=split.shift();body=split.join('\n\n')}let status=null;const m=header.match(/HTTP\/[^ ]+\s+(\d+)/);if(m)status=Number(m[1]);res.json({ok:code===0,status,elapsed,headers:header,body,error:stderr||null})});});
app.use(express.static(path.join(__dirname,'public')));app.get('*',(req,res)=>res.sendFile(path.join(__dirname,'public','index.html')));
app.listen(PORT,async()=>{console.log(`\\n[KELL REST API] Starting on port ${PORT}`);await checkHttpie();console.log(`[KELL REST API] API STATUS: ${apiReady?'READY':'FAILED'}\\n`)});
